import 'package:voices_dating/resources/string_res.dart';

Map<String, String> enStringMap = {
  StringRes.appName: "myLanguage",
  StringRes.man: "Man",
  StringRes.woman: "Woman",
  StringRes.ok: "OK",
  StringRes.signInWithApple: "Sign in with Apple",
  StringRes.signInWithEmail: "Sign up with Email",
  StringRes.signIn: "Sign in",
  StringRes.alreadyMember: "Already a member?",
  StringRes.tncTipPre: "By tapping Sign up or Sign in, you agree to our",
  StringRes.termsOfUse: "Terms of Use",
  StringRes.privacyPolicy: "Privacy Policy",
  StringRes.emailAddress: "Email Address",
  StringRes.forgotPassword: "Forgot Password",
  StringRes.forgotPasswordTips:
      "Please enter the email address you signed\nup with. We’ll send a link with instructions on\ncreating a new password.",
  StringRes.password: "password",
  StringRes.hintForgotPassword: "Forgot Password?",
  StringRes.notHaveAccountTip: "Don't have an account yet?",
  StringRes.signUp: "Sign up",
  StringRes.hintInputEmail: "Input your email",
  StringRes.hintInputPassword: "Input your password",
  StringRes.hintInputUsername: "Input your username",
  StringRes.send: "Send",
  StringRes.myEmail: "My Email",
  StringRes.myPassword: "My Password",
  StringRes.myUserName: "My Username",
  StringRes.iam: "I'm",
  StringRes.labelContinue: "Continue",
  StringRes.labelYourMotherTongue: "Your mother tongue",
  StringRes.labelWhichLanguagePractice:
      "Which language do you want to practice?",
  StringRes.labelMultipleChoices: "Multiple choices",
  StringRes.labelSingleChoices: "Single choices",
  StringRes.myLocation: "My Location",
  StringRes.userCurrentLocation: "Use current location",
  StringRes.country: "Country",
  StringRes.state: "State",
  StringRes.city: "City",
  StringRes.pleaseChoose: "Please choose",
  StringRes.labelBestPhoto: "Best Photo",
  StringRes.labelSignUpUploadPhotoTips:
      "Upload a photo that clearly shows the both of you.",
  StringRes.labelImagePickerNotice:
      "Lewd, offensive, nude, copyrighted, photos with children, and other photos prohibited by law or our Service Agreement are not allowed.",
  StringRes.labelUploadFromLibrary: "Upload from Library",
  StringRes.labelTakeFromCamera: "Take from Camera",
  StringRes.home: "Home",
  StringRes.message: "Message",
  StringRes.discover: "Discover",
  StringRes.upgrade: "Upgrade",
  StringRes.me: "Me",
  StringRes.questions: "Questions",
  StringRes.askQuestion: "Ask a question",
  StringRes.requestView: "Request to View",
  StringRes.delete: "Delete",
  StringRes.report: "Report",
  StringRes.cancel: "Cancel",
  StringRes.confirm: "Confirm",
  StringRes.setAsMainPhoto: "Set as main photo",
  StringRes.makePrivate: "Make private",
  StringRes.makePublic: "Make public",
  StringRes.beTheFirstOne: "Be the first one!",
  StringRes.native: "Native",
  StringRes.practices: "Practices",
  StringRes.sendAMessage: "Send a message",
  StringRes.aboutMe: "About Me",
  StringRes.reply: "Reply",
  StringRes.details: "Details",
  StringRes.addComment: "Add a comment",
  StringRes.newQuestion: "New Question",
  StringRes.addPhotoOrVideo: "ADD PHOTOS",
  StringRes.questionPhotoCountTip: "Upload 9 photos at a time",
  StringRes.description: "Description",
  StringRes.post: "Post",
  StringRes.provideHelp: "Provide Help",
  StringRes.askForHelp: "Ask For Help",
  StringRes.times: "times",
  StringRes.time: "time",
  StringRes.visitors: "Visitors",
  StringRes.vipPrivileges: "Vip Privileges",
  StringRes.verifyNow: "Verify Now!",
  StringRes.editProfile: "Edit Profile",
  StringRes.months: "months",
  StringRes.month: "month",
  StringRes.searchNewPeople: "Search new people",
  StringRes.preview: "Preview",
  StringRes.profilePhoto: "Profile Photo",
  StringRes.labelUserName: "Username",
  StringRes.labelGender: "Gender",
  StringRes.labelAge: "Age",
  StringRes.labelLocation: "Location",
  StringRes.labelLanguage: "Language",
  StringRes.labelMyQuestion: "My Questions",
  StringRes.labelVerifyPhoto: "Verify Photo",
  StringRes.labelAboutMe: "About Me",
  StringRes.done: "Done",
  StringRes.myBirthday: "My Birthday",
  StringRes.settings: "Settings",
  StringRes.account: "Account",
  StringRes.helpAndSupport: "Help and Support",
  StringRes.deleteAccount: "Delete / Disable Account",
  StringRes.logout: "Log Out",
  StringRes.restorePremiumPurchase: "Restore Premium Purchase",
  StringRes.blockedProfiles: "Blocked Profiles",
  StringRes.unblock: "Unblock",
  StringRes.feedback: "Feedback",
  StringRes.topicSubject: "Topic / Subject",
  StringRes.titleFeedbackAttachment:
      "Attachments(Optional, Max 4)",
  StringRes.tipFeedbackAttachment:
      "Do you have a photo or screenshot that would help us?",
  StringRes.titleDeleteAccount: "We are sorry that you are leaving us and would like to know your feedback / suggestions.",
  StringRes.disableHold: "Disable / Hold",
  StringRes.logOutTitle: "Log Out",
  StringRes.verifyByVideo: "Verify By Video",
  StringRes.methodToVerify: "method to verify video",
  StringRes.copyGesture: "Copy the gesture",
  StringRes.faceClearly: "Face clearly visible",
  StringRes.verified: "Verified",
  StringRes.pending: "Pending",
  StringRes.videoVerificationInProgress: "VIDEO VERIFICATION IN PROGRESS",
  StringRes.videoInProgressTip: "Start interacting with other members now!",
  StringRes.searchMatches: "Search Matches",
  StringRes.videoIsUploading: "VIDEO IS UPLOADING",
  StringRes.selectReason: "Select Reason",
  StringRes.comments: "Comments",
  StringRes.confirmPassword: "Confirm password",
  StringRes.block: "Block",
  StringRes.reportReasonTip: "Why are you reporting this user?",
  StringRes.notifications: "Notifications",
  StringRes.goPostQuestion: "Go post a question",
  StringRes.goBrowseQuestion: "Go to browse a question",
  StringRes.acceptHelp: "Accept Help",
  StringRes.myLanguageModel: "My language models",
  StringRes.autoTranslate: "Auto translate",
  StringRes.remove: "Remove",
  StringRes.downloadedLanguageModel: "Downloaded language models",
  StringRes.notNow: "Not now",
  StringRes.labelYes: "Yes",
  StringRes.pullToRefresh : 'Pull to refresh',
  StringRes.releaseReady :  'Release ready',
  StringRes.refreshing :   'Refreshing...',
  StringRes.succeeded : 'Succeeded',
  StringRes.noMore : 'No more',
  StringRes.failed :  'Failed',
  StringRes.lastUpdateAt : 'Last updated at %T',
  StringRes.pullToLoad : "Pull to load",
  StringRes.loading : "Loading...",
  StringRes.uploadSuccess : "Upload Successful",
  StringRes.hours : "hours",
  StringRes.hour : "hour",
  StringRes.days : "days",
  StringRes.day : "day",
  StringRes.justNow: "Just now",
  StringRes.getMoreMatch : "Yes, Get More Matches",
  StringRes.clickYesToNaviPre : "By clicking \"Yes\" button, you agree to our ",
  StringRes.and:"and",

  StringRes.errorEmptyEmail: "Email can not be empty",
  StringRes.errorEmptyUserName: "Username can not be empty",
  StringRes.errorEmptyAge: "User Age can not be empty",
  StringRes.errorInvalidEmail: "Invalid email address",
  StringRes.errorInvalidUserName: "Invalid user name",
  StringRes.errorEmptyPwd: "Password can not be empty",
  StringRes.errorPwdLengthError: "At least 6 characters required",
  StringRes.errorSameNewEmail:
      "The new mailbox cannot be the same as current mailbox",
  StringRes.errorNewPwdNotMach:
      "The new password is inconsistent, please check and re-enter",
  StringRes.errorInputEmail: "Please input email address",
  StringRes.errorUserNameLengthLimit:
      "Please enter a username that is minimum of 3 characters and maximum of 16 characters in length.",
  StringRes.errorImageExit: "Image already exists!",

//tips
  StringRes.needLocationPermission:
      "We need use location for get near by person, please allow to use your Location!",
  StringRes.verifyTips:
      "Verify your account for more chances of being matched!",
  StringRes.addQuestionTips: "Add your question",
  StringRes.hintYouUnsentMsg: "You have unsent a message",
  StringRes.hintUserUnsentMsg: "%s have unsent a message",
  StringRes.hintMinAgeTip: "Must be 19+ to use ${StringRes.appName}",
  StringRes.paymentPageBottomTip:
      "Subscription. Cancel anytime. By tapping on any one of the subscriptions, your payment will be charged to your iTunes account and your subscription will automatically be renewed for the same plan length at the same subscription. Continue to accept our ",
  StringRes.emptyBlockListTip:
      "Members you Block will show up here. Blocked members will never be suggested asa match for you.",
  StringRes.hintFeedbackDesc:
      "Highlight your favorite moments by sharing your luxurious lifestyle here!",
  StringRes.feedbackBottomTip:
      "We will review and respond to your feedback within one working day. Please use clear English. You can also send us an email to\n",
  StringRes.feedbackSuccessTip:
      "Really appreciate the feedback. Feedbacks make our products and services better. We\'ll contact you if we need any further details.",
  StringRes.deleteAccountTips:
      "Deleting your account will permanently delete your account with us.",
  StringRes.disableAccountTips:
      "Once your profile is placed in “HOLD” status, others will not be able to contact you. However, you can release your account from “HOLD” status and reactivate it at any time.",
  StringRes.deleteAccountMemberShipTip:
      "If you are a PREMIUM MEMBER, your membership will expire when it’s supposed to regardless of being disabled or not.",
  StringRes.logoutTips:
      "Are you sure you want to log out? Make sure you can remember your password,as you’ll need it to log back in.",
  StringRes.verifyTitleTip:
      "Get more views and answers\n\nShow credibility and attract serious contact",
  StringRes.verifyMethodTipOne:
      "Hold your device at arm's lengthLook straight ahead.",
  StringRes.verifyMethodTipTwo: "Follow the instructions on the screen.",
  StringRes.verifyBottomTip:
      "Note: The verified logo will be canceled if you delete all pictures from your profile.\n\nAll information you provide is kept confidential. Youcan use this verification to prove that your profile photos are real photos of you.",
  StringRes.hintTellUsMore: "Tell us more..",
  StringRes.successDeleteAccountTitle:
      "You have resigned from ${StringRes.appName}.\nThank you for using ${StringRes.appName}",
  StringRes.successDeleteAccountTips:
      "To avoid wrongful decision, your information will be kept in our database for two months. You may contact us within two months to retrieve and reactivate your account, otherwise it will be deleted permanently.",
  StringRes.successDisableAccountTips:
      "Your account has been\nsuccessfully disable!",
  StringRes.hintComposeMessage: "Compost a message",
  StringRes.emptyDataNotice: "No data yet!",
  StringRes.reportSuccessTips: "Thanks for reporting. We\'ll look into it!",
  StringRes.replyYourCommentTip: "replies to  your comment",
  StringRes.answerYouQuestion: "Answered Your Question",
  StringRes.emptyMyQuestionTip: "Post your own question!",
  StringRes.emptyVisitorTip:
      "No new views yes.\n\nCheck out some search results just for you now!",
  StringRes.emptyAcceptHelpTip: "You haven't gotten help yet.",
  StringRes.emptyProvideHelpTip: "You haven't helped anyone yet.",
  StringRes.tipsEmailResetMessage:
      "If you don't receive an email from us within a couple of minutes, make sure to check your spam folder or send us an email from our.",
  StringRes.changeAvatarSuccess: "Update successful!",
  StringRes.autoTranslateTips:
      "(Auto translate questions and messages for you.)",
  StringRes.downloadRecommendLanguageTip:
      "For enhanced your experience, we highly recommend downloading the following language models first. This way, we can provide you with automatic translation services, allowing you to learn various languages more effectively.",
  StringRes.goSettingPageDownloadTip:
      "You can enter the settings page at any time to download the models.",
  StringRes.changeGenderTip:
      "Are you sure you want to modify it? You can only modify gender once.",
  StringRes.deleteContactTip:
      "Want to delete this conversation?",
  StringRes.navigateTip : "Do you want to meet more attractive singles for sugar relationships?",
  StringRes.reactiveAccountTip : "Your account is currently disabled. Would you like to reactivate it and post your profile online again?",

  //Premium feature
  StringRes.premiumUnlimitedMessage: "Unlimited Messages",
  StringRes.premiumUnlimitedMessageHint:
      "Initiate messages to anyone you like!",
  StringRes.premiumRevealSecretAdmirers: "Reveal Secret Admirers",
  StringRes.premiumRevealSecretAdmirersHint:
      "Unlock members that are interested.",
  StringRes.premiumUnblockMember: "Unlock members that are interested.",
  StringRes.premiumUnblockMemberHint:
      "See the complete list of your visitors!",
  StringRes.premiumDistinguishedStatus: "Distinguished Status Symbol",
  StringRes.premiumDistinguishedStatusHint:
      "Stand out with the PREMIUM Emblem.",
  StringRes.premiumExclusiveFeature: "10+ Exclusive Features",
  StringRes.premiumExclusiveFeatureHint:
      "Initiate messages to anyone you like!",

  StringRes.reportReasonOnly:
      "Online-only relationship or selling personal photos / videos",
  StringRes.reportReasonLookingForSugar:
      "Looking for a sugar daddy relationship",
  StringRes.reportReasonAskMoney: "Asked for money before meeting",
  StringRes.reportReasonSpam: "Spam / scam / fake",
  StringRes.reportReasonOffensive: "Offensive / abusive / violent",
  StringRes.reportReasonInappropriate: "Inappropriate or obscene content",
  StringRes.reportReasonTriedOtherService: "Tried to solicit other services",
  StringRes.reportReasonUnderage: "Underage",
  StringRes.reportReasonOther: "other",

  StringRes.feedbackMemberShip:
      "PREMIUM MEMBERSHIP / Payment / Billing issues",
  StringRes.feedbackLogin: "Login / Password",
  StringRes.feedbackLoginAccount: "Registration / Account",
  StringRes.feedbackPhotos: "Photos / Profile",
  StringRes.feedbackQuestions: "Questions",
  StringRes.feedbackMessage: "Messages",
  StringRes.feedbackTechnical: "Technical issues",
  StringRes.feedbackResignation: "Resignation",
  StringRes.feedbackSuggestions: "Suggestions",
  StringRes.feedbackOther: "Other",
  StringRes.suspendTip:"There seems to be unusual activity on your account so for your safety is has been temporarily suspended.",
  StringRes.contactUs:"Contact Us",

  "United States": "United States",
  "Canada": "Canada",
  "United Kingdom": "United Kingdom",
  "Afghanistan": "Afghanistan",
  "Åland": "Åland",
  "Albania": "Albania",
  "Algeria": "Algeria",
  "American Samoa": "American Samoa",
  "Andorra": "Andorra",
  "Angola": "Angola",
  "Anguilla": "Anguilla",
  "Antarctica": "Antarctica",
  "Antigua and Barbuda": "Antigua and Barbuda",
  "Argentina": "Argentina",
  "Armenia": "Armenia",
  "Aruba": "Aruba",
  "Australia": "Australia",
  "Austria": "Austria",
  "Azerbaijan": "Azerbaijan",
  "Bahamas": "Bahamas",
  "Bahrain": "Bahrain",
  "Bangladesh": "Bangladesh",
  "Barbados": "Barbados",
  "Belarus": "Belarus",
  "Belgium": "Belgium",
  "Belize": "Belize",
  "Benin": "Benin",
  "Bermuda": "Bermuda",
  "Bhutan": "Bhutan",
  "Bolivia": "Bolivia",
  "Bonaire, Sint Eustatius, and Saba": "Bonaire, Sint Eustatius, and Saba",
  "Bosnia and Herzegovina": "Bosnia and Herzegovina",
  "Botswana": "Botswana",
  "Bouvet Island": "Bouvet Island",
  "Brazil": "Brazil",
  "British Indian Ocean Territory": "British Indian Ocean Territory",
  "British Virgin Islands": "British Virgin Islands",
  "Brunei": "Brunei",
  "Bulgaria": "Bulgaria",
  "Burkina Faso": "Burkina Faso",
  "Burundi": "Burundi",
  "Cabo Verde": "Cabo Verde",
  "Cambodia": "Cambodia",
  "Cameroon": "Cameroon",
  "Cayman Islands": "Cayman Islands",
  "Central African Republic": "Central African Republic",
  "Chad": "Chad",
  "Chile": "Chile",
  "China": "China",
  "Christmas Island": "Christmas Island",
  "Cocos [Keeling] Islands": "Cocos [Keeling] Islands",
  "Colombia": "Colombia",
  "Comoros": "Comoros",
  "Congo": "Congo",
  "Cook Islands": "Cook Islands",
  "Costa Rica": "Costa Rica",
  "Croatia": "Croatia",
  "Cuba": "Cuba",
  "Curaçao": "Curaçao",
  "Cyprus": "Cyprus",
  "Czechia": "Czechia",
  "Democratic Republic of Timor-Leste": "Democratic Republic of Timor-Leste",
  "Denmark": "Denmark",
  "Djibouti": "Djibouti",
  "Dominica": "Dominica",
  "Dominican Republic": "Dominican Republic",
  "Ecuador": "Ecuador",
  "Egypt": "Egypt",
  "El Salvador": "El Salvador",
  "Equatorial Guinea": "Equatorial Guinea",
  "Eritrea": "Eritrea",
  "Estonia": "Estonia",
  "Eswatini": "Eswatini",
  "Ethiopia": "Ethiopia",
  "Falkland Islands": "Falkland Islands",
  "Faroe Islands": "Faroe Islands",
  "Federated States of Micronesia": "Federated States of Micronesia",
  "Fiji": "Fiji",
  "Finland": "Finland",
  "France": "France",
  "French Guiana": "French Guiana",
  "French Polynesia": "French Polynesia",
  "French Southern Territories": "French Southern Territories",
  "Gabon": "Gabon",
  "Gambia": "Gambia",
  "Georgia": "Georgia",
  "Germany": "Germany",
  "Ghana": "Ghana",
  "Gibraltar": "Gibraltar",
  "Greece": "Greece",
  "Greenland": "Greenland",
  "Grenada": "Grenada",
  "Guadeloupe": "Guadeloupe",
  "Guam": "Guam",
  "Guatemala": "Guatemala",
  "Guernsey": "Guernsey",
  "Guinea": "Guinea",
  "Guinea-Bissau": "Guinea-Bissau",
  "Guyana": "Guyana",
  "Haiti": "Haiti",
  "Hashemite Kingdom of Jordan": "Hashemite Kingdom of Jordan",
  "Heard Island and McDonald Islands": "Heard Island and McDonald Islands",
  "Honduras": "Honduras",
  "Hong Kong": "Hong Kong",
  "Hungary": "Hungary",
  "Iceland": "Iceland",
  "India": "India",
  "Indonesia": "Indonesia",
  "Iran": "Iran",
  "Iraq": "Iraq",
  "Ireland": "Ireland",
  "Isle of Man": "Isle of Man",
  "Israel": "Israel",
  "Italy": "Italy",
  "Ivory Coast": "Ivory Coast",
  "Jamaica": "Jamaica",
  "Japan": "Japan",
  "Jersey": "Jersey",
  "Kazakhstan": "Kazakhstan",
  "Kenya": "Kenya",
  "Kiribati": "Kiribati",
  "Kosovo": "Kosovo",
  "Kuwait": "Kuwait",
  "Kyrgyzstan": "Kyrgyzstan",
  "Laos": "Laos",
  "Latvia": "Latvia",
  "Lebanon": "Lebanon",
  "Lesotho": "Lesotho",
  "Liberia": "Liberia",
  "Libya": "Libya",
  "Liechtenstein": "Liechtenstein",
  "Luxembourg": "Luxembourg",
  "Macao": "Macao",
  "Madagascar": "Madagascar",
  "Malawi": "Malawi",
  "Malaysia": "Malaysia",
  "Maldives": "Maldives",
  "Mali": "Mali",
  "Malta": "Malta",
  "Marshall Islands": "Marshall Islands",
  "Martinique": "Martinique",
  "Mauritania": "Mauritania",
  "Mauritius": "Mauritius",
  "Mayotte": "Mayotte",
  "Mexico": "Mexico",

  "Monaco": "Monaco",
  "Mongolia": "Mongolia",
  "Montenegro": "Montenegro",
  "Montserrat": "Montserrat",
  "Morocco": "Morocco",
  "Mozambique": "Mozambique",
  "Myanmar": "Myanmar",
  "Namibia": "Namibia",
  "Nauru": "Nauru",
  "Nepal": "Nepal",
  "Netherlands": "Netherlands",
  "New Caledonia": "New Caledonia",
  "New Zealand": "New Zealand",
  "Nicaragua": "Nicaragua",
  "Niger": "Niger",
  "Nigeria": "Nigeria",
  "Niue": "Niue",
  "Norfolk Island": "Norfolk Island",
  "Northern Mariana Islands": "Northern Mariana Islands",
  "North Korea": "North Korea",
  "North Macedonia": "North Macedonia",
  "Norway": "Norway",
  "Oman": "Oman",
  "Pakistan": "Pakistan",
  "Palau": "Palau",
  "Palestine": "Palestine",
  "Panama": "Panama",
  "Papua New Guinea": "Papua New Guinea",
  "Paraguay": "Paraguay",
  "Peru": "Peru",
  "Philippines": "Philippines",
  "Pitcairn Islands": "Pitcairn Islands",
  "Poland": "Poland",
  "Portugal": "Portugal",
  "Puerto Rico": "Puerto Rico",
  "Qatar": "Qatar",
  "Republic of Lithuania": "Republic of Lithuania",
  "Republic of Moldova": "Republic of Moldova",
  "Republic of the Congo": "Republic of the Congo",
  "Réunion": "Réunion",
  "Romania": "Romania",
  "Russia": "Russia",
  "Rwanda": "Rwanda",
  "Saint Barthélemy": "Saint Barthélemy",
  "Saint Helena": "Saint Helena",
  "Saint Lucia": "Saint Lucia",
  "Saint Martin": "Saint Martin",
  "Saint Pierre and Miquelon": "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines",
  "Samoa": "Samoa",
  "San Marino": "San Marino",
  "São Tomé and Príncipe": "São Tomé and Príncipe",
  "Saudi Arabia": "Saudi Arabia",
  "Senegal": "Senegal",
  "Serbia": "Serbia",
  "Seychelles": "Seychelles",
  "Sierra Leone": "Sierra Leone",
  "Singapore": "Singapore",
  "Sint Maarten": "Sint Maarten",
  "Slovakia": "Slovakia",
  "Slovenia": "Slovenia",
  "Solomon Islands": "Solomon Islands",
  "Somalia": "Somalia",
  "South Africa": "South Africa",
  "South Georgia and the South Sandwich Islands":
      "South Georgia and the South Sandwich Islands",
  "South Korea": "South Korea",
  "South Sudan": "South Sudan",
  "Spain": "Spain",
  "Sri Lanka": "Sri Lanka",
  "St Kitts and Nevis": "St Kitts and Nevis",
  "Sudan": "Sudan",
  "Suriname": "Suriname",
  "Svalbard and Jan Mayen": "Svalbard and Jan Mayen",
  "Sweden": "Sweden",
  "Switzerland": "Switzerland",
  "Syria": "Syria",
  "Taiwan": "Taiwan",
  "Tajikistan": "Tajikistan",
  "Tanzania": "Tanzania",
  "Thailand": "Thailand",
  "Togo": "Togo",
  "Tokelau": "Tokelau",
  "Tonga": "Tonga",
  "Trinidad and Tobago": "Trinidad and Tobago",
  "Tunisia": "Tunisia",
  "Turkey": "Turkey",
  "Turkmenistan": "Turkmenistan",
  "Turks and Caicos Islands": "Turks and Caicos Islands",
  "Tuvalu": "Tuvalu",
  "Uganda": "Uganda",
  "Ukraine": "Ukraine",
  "United Arab Emirates": "United Arab Emirates",
  "Uruguay": "Uruguay",
  "U.S. Minor Outlying Islands": "U.S. Minor Outlying Islands",
  "U.S. Virgin Islands": "U.S. Virgin Islands",
  "Uzbekistan": "Uzbekistan",
  "Vanuatu": "Vanuatu",
  "Vatican City": "Vatican City",
  "Venezuela": "Venezuela",
  "Vietnam": "Vietnam",
  "Wallis and Futuna": "Wallis and Futuna",
  "Western Sahara": "Western Sahara",
  "Yemen": "Yemen",
  "Zambia": "Zambia",
  "Zimbabwe": "Zimbabwe"
};

// }
