import '../string_res.dart';

Map<String, String> frStringMap = {
  StringRes.appName: "maLangue",
  StringRes.man: "Homme",
  StringRes.woman: "Femme",
  StringRes.ok: "OK",
  StringRes.signInWithApple: "Se connecter avec Apple",
  StringRes.signInWithEmail: "Inscription avec Email",
  StringRes.signIn: "Se connecter",
  StringRes.alreadyMember: "Déjà membre ?",
  StringRes.tncTipPre:
      "En appuyant sur S'inscrire ou Se connecter, vous acceptez nos",
  StringRes.termsOfUse: "Conditions d'utilisation",
  StringRes.privacyPolicy: "Politique de confidentialité",
  StringRes.emailAddress: "Adresse e-mail",
  StringRes.forgotPassword: "Mot de passe oublié",
  StringRes.forgotPasswordTips:
      "Veuillez saisir l'adresse e-mail avec laquelle vous vous êtes inscrit\nNous vous enverrons un lien avec des instructions pour\ncréer un nouveau mot de passe.",
  StringRes.password: "mot de passe",
  StringRes.hintForgotPassword: "Mot de passe oublié ?",
  StringRes.notHaveAccountTip: "Vous n'avez pas encore de compte ?",
  StringRes.signUp: "S'inscrire",
  StringRes.hintInputEmail: "Saisissez votre e-mail",
  StringRes.hintInputPassword: "Saisissez votre mot de passe",
  StringRes.hintInputUsername: "Entrez votre nom d'utilisateur",
  StringRes.send: "Envoyer",
  StringRes.myEmail: "Mon Email",
  StringRes.myPassword: "Mon Mot de passe",
  StringRes.myUserName: "Mon Nom d'utilisateur",
  StringRes.iam: "Je suis",
  StringRes.labelContinue: "Continuer",
  StringRes.labelYourMotherTongue: "Votre langue maternelle",
  StringRes.labelWhichLanguagePractice:
      "Quelle langue voulez-vous pratiquer ?",
  StringRes.labelMultipleChoices: "Choix multiples",
  StringRes.labelSingleChoices: "Choix simples",
  StringRes.myLocation: "Ma position",
  StringRes.userCurrentLocation: "Utiliser la position actuelle",
  StringRes.country: "Pays",
  StringRes.state: "État",
  StringRes.city: "Ville",
  StringRes.pleaseChoose: "Veuillez choisir",
  StringRes.labelBestPhoto: "Meilleure photo",
  StringRes.labelSignUpUploadPhotoTips:
      "Téléchargez une photo qui montre clairement vous deux.",
  StringRes.labelImagePickerNotice:
      "Les photos obscènes, offensantes, nues, protégées par des droits d'auteur, avec des enfants, et d'autres photos interdites par la loi ou notre Accord de service ne sont pas autorisées.",
  StringRes.labelUploadFromLibrary: "Télécharger depuis la bibliothèque",
  StringRes.labelTakeFromCamera: "Prendre depuis la caméra",
  StringRes.home: "Accueil",
  StringRes.message: "Message",
  StringRes.discover: "Découvrir",
  StringRes.upgrade: "Mise à niveau",
  StringRes.me: "Moi",
  StringRes.questions: "Questions",
  StringRes.askQuestion: "Poser une question",
  StringRes.requestView: "Demande de visualisation",
  StringRes.delete: "Supprimer",
  StringRes.report: "Signaler",
  StringRes.cancel: "Annuler",
  StringRes.confirm: "Confirmer",
  StringRes.setAsMainPhoto: "Définir comme photo principale",
  StringRes.makePrivate: "Rendre privé",
  StringRes.makePublic: "Rendre public",
  StringRes.beTheFirstOne: "Soyez le premier !",
  StringRes.native: "Native",
  StringRes.practices: "Pratiques",
  StringRes.sendAMessage: "Envoyer un message",
  StringRes.aboutMe: "À propos de moi",
  StringRes.reply: "Répondre",
  StringRes.details: "Détails",
  StringRes.addComment: "Ajouter un commentaire",
  StringRes.newQuestion: "Nouvelle question",
  StringRes.addPhotoOrVideo: "AJOUTER DES PHOTOS",
  StringRes.questionPhotoCountTip: "Téléchargez 9 photos à la fois",
  StringRes.description: "Description",
  StringRes.post: "Poster",
  StringRes.provideHelp: "Fournir de l'aide",
  StringRes.askForHelp: "Demande d'aide",
  StringRes.times: "fois",
  StringRes.time: "temps",
  StringRes.visitors: "Visiteurs",
  StringRes.vipPrivileges: "Privilèges VIP",
  StringRes.verifyNow: "Vérifier maintenant !",
  StringRes.editProfile: "Éditer le profil",
  StringRes.months: "mois",
  StringRes.month: "mois",
  StringRes.searchNewPeople: "Chercher de nouvelles personnes",
  StringRes.preview: "Aperçu",
  StringRes.profilePhoto: "Photo de profil",
  StringRes.labelUserName: "Nom d'utilisateur",
  StringRes.labelGender: "Genre",
  StringRes.labelAge: "Âge",
  StringRes.labelLocation: "Emplacement",
  StringRes.labelLanguage: "Langue",
  StringRes.labelMyQuestion: "Mes questions",
  StringRes.labelVerifyPhoto: "Vérifier la photo",
  StringRes.labelAboutMe: "À propos de moi",
  StringRes.done: "Fait",
  StringRes.myBirthday: "Mon anniversaire",
  StringRes.settings: "Paramètres",
  StringRes.account: "Compte",
  StringRes.helpAndSupport: "Aide et support",
  StringRes.deleteAccount: "Supprimer/Désactiver le compte",
  StringRes.logout: "Déconnexion",
  StringRes.restorePremiumPurchase: "Restaurer l'achat premium",
  StringRes.blockedProfiles: "Profils bloqués",
  StringRes.unblock: "Débloquer",
  StringRes.feedback: "Retour d'information",
  StringRes.topicSubject: "Sujet / Sujet",
  StringRes.titleFeedbackAttachment:
      "Pièces jointes (Facultatif, Max 4)",
  StringRes.tipFeedbackAttachment:
      "Avez-vous une photo ou une capture d'écran qui pourrait nous aider ?",
  StringRes.titleDeleteAccount: "Nous sommes désolés que vous nous quittiez et aimerions connaître vos commentaires / suggestions.",
  StringRes.disableHold: "Désactiver / Mettre en attente",
  StringRes.logOutTitle: "Déconnexion",
  StringRes.verifyByVideo: "Vérification par vidéo",
  StringRes.methodToVerify: "Méthode pour vérifier la vidéo",
  StringRes.copyGesture: "Copier le geste",
  StringRes.faceClearly: "Visage clairement visible",
  StringRes.verified: "Vérifié",
  StringRes.pending: "En attente",
  StringRes.videoVerificationInProgress: "VÉRIFICATION VIDÉO EN COURS",
  StringRes.videoInProgressTip:
      "Commencez à interagir avec les autres membres maintenant !",
  StringRes.searchMatches: "Rechercher des correspondances",
  StringRes.videoIsUploading: "LA VIDÉO EST EN COURS DE TÉLÉCHARGEMENT",
  StringRes.selectReason: "Sélectionner une raison",
  StringRes.comments: "Commentaires",
  StringRes.confirmPassword: "Confirmer le mot de passe",
  StringRes.block: "Bloquer",
  StringRes.reportReasonTip: "Pourquoi signalez-vous cet utilisateur ?",
  StringRes.notifications: "Notifications",
  StringRes.goPostQuestion: "Aller poser une question",
  StringRes.goBrowseQuestion: "Aller parcourir une question",
  StringRes.acceptHelp: "Accepter l'aide",
  StringRes.myLanguageModel: "Mes modèles de langues",
  StringRes.autoTranslate: "Traduction automatique",
  StringRes.remove: "Supprimer",
  StringRes.downloadedLanguageModel: "Modèles de langues téléchargés",
  StringRes.notNow: "Pas maintenant",
  StringRes.labelYes: "Oui",
  StringRes.pullToRefresh : 'Tirer pour rafraîchir',
  StringRes.releaseReady :  'Sortie prête',
  StringRes.refreshing :   'rafraîchissante...',
  StringRes.succeeded : 'Réussie',
  StringRes.noMore : 'Pas plus',
  StringRes.failed :  'Échoué',
  StringRes.lastUpdateAt : 'Dernière mise à jour à %T',
  StringRes.pullToLoad : "Tirer pour charger",
  StringRes.loading : "Chargement...",
  StringRes.uploadSuccess : "Téléchargement réussi",
  StringRes.hours : "heures",
  StringRes.hour : "heure",
  StringRes.days : "jours",
  StringRes.day : "jour",
  StringRes.justNow: "Tout à l' heure",
  StringRes.getMoreMatch : "Oui, Obtenez plus de correspondances",
  StringRes.clickYesToNaviPre : "En cliquant sur le bouton \"Oui\", vous acceptez nos ",
  StringRes.and:"et",

  StringRes.errorEmptyEmail: "L'e-mail ne peut pas être vide",
  StringRes.errorEmptyUserName: "Le nom d'utilisateur ne peut pas être vide",
  StringRes.errorEmptyAge: "L'âge de l'utilisateur ne peut pas être vide",
  StringRes.errorInvalidEmail: "Adresse e-mail invalide",
  StringRes.errorInvalidUserName: "Nom d'utilisateur invalide",
  StringRes.errorEmptyPwd: "Le mot de passe ne peut pas être vide",
  StringRes.errorPwdLengthError: "Au moins 6 caractères requis",
  StringRes.errorSameNewEmail:
      "La nouvelle adresse e-mail ne peut pas être la même que l'adresse actuelle",
  StringRes.errorNewPwdNotMach:
      "Le nouveau mot de passe n'est pas conforme, veuillez vérifier et saisir à nouveau",
  StringRes.errorInputEmail: "Veuillez saisir une adresse e-mail",
  StringRes.errorUserNameLengthLimit:
      "Veuillez saisir un nom d'utilisateur d'au moins 3 caractères et d'au plus 16 caractères de long.",
  StringRes.errorImageExit: "L'image existe déjà !",
//tips
  StringRes.needLocationPermission:
      "Nous avons besoin de la localisation pour trouver des personnes à proximité, veuillez autoriser l'utilisation de votre emplacement !",
  StringRes.verifyTips:
      "Vérifiez votre compte pour avoir plus de chances d'être assorti !",
  StringRes.addQuestionTips: "Ajoutez votre question",
  StringRes.hintYouUnsentMsg: "Vous avez un message non envoyé",
  StringRes.hintUserUnsentMsg: "%s a un message non envoyé",
  StringRes.hintMinAgeTip:
      "Vous devez avoir 19 ans ou plus pour utiliser ${StringRes.appName}",
  StringRes.paymentPageBottomTip:
      "Abonnement. Annulez à tout moment. En appuyant sur l'un des abonnements, votre paiement sera prélevé sur votre compte iTunes et votre abonnement sera automatiquement renouvelé pour la même durée et au même tarif d'abonnement. Continuez à accepter nos ",
  StringRes.emptyBlockListTip:
      "Les membres que vous bloquez apparaîtront ici. Les membres bloqués ne vous seront jamais suggérés comme correspondance.",
  StringRes.hintFeedbackDesc:
      "Mettez en valeur vos moments préférés en partageant votre style de vie luxueux ici !",
  StringRes.feedbackBottomTip:
      "Nous examinerons et répondrons à vos commentaires dans un délai d'un jour ouvrable. Veuillez utiliser un anglais clair. Vous pouvez également nous envoyer un e-mail à\n",
  StringRes.feedbackSuccessTip:
      "Nous apprécions vraiment les commentaires. Les retours d'information améliorent nos produits et services. Nous vous contacterons si nous avons besoin de plus de détails.",
  StringRes.deleteAccountTips:
      "La suppression de votre compte supprimera définitivement votre compte chez nous.",
  StringRes.disableAccountTips:
      "Une fois que votre profil est placé en statut \"ATTENTE\", les autres ne pourront pas vous contacter. Cependant, vous pouvez libérer votre compte de l'état \"ATTENTE\" et le réactiver à tout moment.",
  StringRes.deleteAccountMemberShipTip:
      "Si vous êtes MEMBRE PREMIUM, votre adhésion expirera comme prévu, que votre compte soit désactivé ou non.",
  StringRes.logoutTips:
      "Êtes-vous sûr de vouloir vous déconnecter ? Assurez-vous de vous rappeler de votre mot de passe, car vous en aurez besoin pour vous reconnecter.",
  StringRes.verifyTitleTip:
      "Obtenez plus de vues et de réponses\n\nMontrez votre crédibilité et attirez des contacts sérieux",
  StringRes.verifyMethodTipOne:
      "Tenez votre appareil à bout de bras. Regardez droit devant.",
  StringRes.verifyMethodTipTwo: "Suivez les instructions à l'écran.",
  StringRes.verifyBottomTip:
      "Remarque : Le logo vérifié sera annulé si vous supprimez toutes les photos de votre profil.\n\nToutes les informations que vous fournissez sont confidentielles. Vous pouvez utiliser cette vérification pour prouver que vos photos de profil sont de vraies photos de vous.",
  StringRes.hintTellUsMore: "Dites-nous-en plus...",
  StringRes.successDeleteAccountTitle:
      "Vous avez démissionné de ${StringRes.appName}.\nMerci d'avoir utilisé ${StringRes.appName}",
  StringRes.successDeleteAccountTips:
      "Pour éviter une décision erronée, vos informations seront conservées dans notre base de données pendant deux mois. Vous pouvez nous contacter dans les deux mois pour récupérer et réactiver votre compte, sinon il sera supprimé définitivement.",
  StringRes.successDisableAccountTips:
      "Votre compte a été\ndésactivé avec succès !",
  StringRes.hintComposeMessage: "Composer un message",
  StringRes.emptyDataNotice: "Pas encore de données !",
  StringRes.reportSuccessTips:
      "Merci pour le signalement. Nous examinerons cela !",
  StringRes.replyYourCommentTip: "répond à votre commentaire",
  StringRes.answerYouQuestion: "A répondu à votre question",
  StringRes.emptyMyQuestionTip: "Publiez votre propre question !",
  StringRes.emptyVisitorTip:
      "Aucune nouvelle vue pour l'instant.\n\nDécouvrez maintenant quelques résultats de recherche qui vous sont spécialement dédiés !",
  StringRes.emptyAcceptHelpTip: "Vous n'avez pas encore reçu d'aide.",
  StringRes.emptyProvideHelpTip: "Vous n'avez encore aidé personne.",
  StringRes.tipsEmailResetMessage:
      "Si vous ne recevez pas d'e-mail de notre part dans les quelques minutes, assurez-vous de vérifier votre dossier de courrier indésirable ou envoyez-nous un e-mail depuis notre.",
  StringRes.changeAvatarSuccess: "Mise à jour réussie !",
  StringRes.autoTranslateTips:
      "(Traduire automatiquement les questions et les messages pour vous.)",
  StringRes.downloadRecommendLanguageTip:
      "Pour améliorer votre expérience, nous vous recommandons vivement de télécharger d'abord les modèles de langues suivants. Ainsi, nous pouvons vous fournir des services de traduction automatique, vous permettant d'apprendre différentes langues de manière plus efficace.",
  StringRes.goSettingPageDownloadTip:
      "Vous pouvez accéder à la page des paramètres à tout moment pour télécharger les modèles.",
  StringRes.changeGenderTip:
      "Êtes-vous sûr de vouloir le modifier ? Vous ne pouvez modifier le genre qu'une seule fois.",
  StringRes.deleteContactTip:
      "Voulez-vous supprimer cette conversation?",
  StringRes.navigateTip : "Souhaitez-vous rencontrer davantage de célibataires séduisants pour des relations sucrées ?",
  StringRes.reactiveAccountTip : "Votre compte est actuellement désactivé. Souhaitez-vous le réactiver et publier à nouveau votre profil en ligne ?",


  //Premium feature
  StringRes.premiumUnlimitedMessage: "Messages illimités",
  StringRes.premiumUnlimitedMessageHint:
      "Initiez des messages à qui vous voulez !",
  StringRes.premiumRevealSecretAdmirers: "Révélez les admirateurs secrets",
  StringRes.premiumRevealSecretAdmirersHint:
      "Déverrouillez les membres intéressés.",
  StringRes.premiumUnblockMember: "Débloquer les membres",
  StringRes.premiumUnblockMemberHint:
      "Consultez la liste complète de vos visiteurs !",
  StringRes.premiumDistinguishedStatus: "Symbole de statut distingué",
  StringRes.premiumDistinguishedStatusHint:
      "Démarquez-vous avec l'emblème PREMIUM.",
  StringRes.premiumExclusiveFeature: "10+ Fonctionnalités exclusives",
  StringRes.premiumExclusiveFeatureHint:
      "Initiez des messages à qui vous voulez !",

  StringRes.reportReasonOnly:
      "Relation uniquement en ligne ou vente de photos / vidéos personnelles",
  StringRes.reportReasonLookingForSugar:
      "Recherche une relation avec un sugar daddy",
  StringRes.reportReasonAskMoney: "A demandé de l'argent avant la rencontre",
  StringRes.reportReasonSpam: "Spam / arnaque / faux",
  StringRes.reportReasonOffensive: "Contenu offensant / abusif / violent",
  StringRes.reportReasonInappropriate: "Contenu inapproprié ou obscène",
  StringRes.reportReasonTriedOtherService:
      "A tenté de solliciter d'autres services",
  StringRes.reportReasonUnderage: "Mineur(e)",
  StringRes.reportReasonOther: "autre",

  StringRes.feedbackMemberShip:
      "Adhésion PREMIUM / Problèmes de paiement / Facturation",
  StringRes.feedbackLogin: "Connexion / Mot de passe",
  StringRes.feedbackLoginAccount: "Inscription / Compte",
  StringRes.feedbackPhotos: "Photos / Profil",
  StringRes.feedbackQuestions: "Questions",
  StringRes.feedbackMessage: "Messages",
  StringRes.feedbackTechnical: "Problèmes techniques",
  StringRes.feedbackResignation: "Démission",
  StringRes.feedbackSuggestions: "Suggestions",
  StringRes.feedbackOther: "Autre",
  StringRes.suspendTip:"Il semble y avoir une activité inhabituelle sur votre compte, c'est pourquoi il a été temporairement suspendu pour des raisons de sécurité.",
  StringRes.contactUs:"Contactez-nous",

  "United States": "États-Unis",
  "Canada": "Canada",
  "United Kingdom": "Royaume-Uni",
  "Afghanistan": "Afghanistan",
  "Åland": "Åland",
  "Albania": "Albanie",
  "Algeria": "Algérie",
  "American Samoa": "Samoa américaines",
  "Andorra": "Andorre",
  "Angola": "Angola",
  "Anguilla": "Anguilla",
  "Antarctica": "Antarctique",
  "Antigua and Barbuda": "Antigua-et-Barbuda",
  "Argentina": "Argentine",
  "Armenia": "Arménie",
  "Aruba": "Aruba",
  "Australia": "Australie",
  "Austria": "Autriche",
  "Azerbaijan": "Azerbaïdjan",
  "Bahamas": "Bahamas",
  "Bahrain": "Bahreïn",
  "Bangladesh": "Bangladesh",
  "Barbados": "Barbade",
  "Belarus": "Biélorussie",
  "Belgium": "Belgique",
  "Belize": "Belize",
  "Benin": "Bénin",
  "Bermuda": "Bermudes",
  "Bhutan": "Bhoutan",
  "Bolivia": "Bolivie",
  "Bonaire, Sint Eustatius, and Saba": "Bonaire, Saint-Eustache et Saba",
  "Bosnia and Herzegovina": "Bosnie-Herzégovine",
  "Botswana": "Botswana",
  "Bouvet Island": "Île Bouvet",
  "Brazil": "Brésil",
  "British Indian Ocean Territory": "Territoire britannique de l'océan Indien",
  "British Virgin Islands": "Îles Vierges britanniques",
  "Brunei": "Brunei",
  "Bulgaria": "Bulgarie",
  "Burkina Faso": "Burkina Faso",
  "Burundi": "Burundi",
  "Cabo Verde": "Cap-Vert",
  "Cambodia": "Cambodge",
  "Cameroon": "Cameroun",
  "Cayman Islands": "Îles Caïmans",
  "Central African Republic": "République centrafricaine",
  "Chad": "Tchad",
  "Chile": "Chili",
  "China": "Chine",
  "Christmas Island": "Île Christmas",
  "Cocos [Keeling] Islands": "Îles Cocos [Keeling]",
  "Colombia": "Colombie",
  "Comoros": "Comores",
  "Congo": "Congo",
  "Cook Islands": "Îles Cook",
  "Costa Rica": "Costa Rica",
  "Croatia": "Croatie",
  "Cuba": "Cuba",
  "Curaçao": "Curaçao",
  "Cyprus": "Chypre",
  "Czechia": "Tchéquie",
  "Democratic Republic of Timor-Leste":
      "République démocratique du Timor-Leste",
  "Denmark": "Danemark",
  "Djibouti": "Djibouti",
  "Dominica": "Dominique",
  "Dominican Republic": "République dominicaine",
  "Ecuador": "Équateur",
  "Egypt": "Égypte",
  "El Salvador": "Salvador",
  "Equatorial Guinea": "Guinée équatoriale",
  "Eritrea": "Érythrée",
  "Estonia": "Estonie",
  "Eswatini": "Eswatini",
  "Ethiopia": "Éthiopie",
  "Falkland Islands": "Îles Malouines",
  "Faroe Islands": "Îles Féroé",
  "Federated States of Micronesia": "États fédérés de Micronésie",
  "Fiji": "Fidji",
  "Finland": "Finlande",
  "France": "France",
  "French Guiana": "Guyane française",
  "French Polynesia": "Polynésie française",
  "French Southern Territories": "Terres australes françaises",
  "Gabon": "Gabon",
  "Gambia": "Gambie",
  "Georgia": "Géorgie",
  "Germany": "Allemagne",
  "Ghana": "Ghana",
  "Gibraltar": "Gibraltar",
  "Greece": "Grèce",
  "Greenland": "Groenland",
  "Grenada": "Grenade",
  "Guadeloupe": "Guadeloupe",
  "Guam": "Guam",
  "Guatemala": "Guatemala",
  "Guernsey": "Guernesey",
  "Guinea": "Guinée",
  "Guinea-Bissau": "Guinée-Bissau",
  "Guyana": "Guyana",
  "Haiti": "Haïti",
  "Hashemite Kingdom of Jordan": "Royaume hachémite de Jordanie",
  "Heard Island and McDonald Islands": "Îles Heard et McDonald",
  "Honduras": "Honduras",
  "Hong Kong": "Hong Kong",
  "Hungary": "Hongrie",
  "Iceland": "Islande",
  "India": "Inde",
  "Indonesia": "Indonésie",
  "Iran": "Iran",
  "Iraq": "Irak",
  "Ireland": "Irlande",
  "Isle of Man": "Île de Man",
  "Israel": "Israël",
  "Italy": "Italie",
  "Ivory Coast": "Côte d'Ivoire",
  "Jamaica": "Jamaïque",
  "Japan": "Japon",
  "Jersey": "Jersey",
  "Kazakhstan": "Kazakhstan",
  "Kenya": "Kenya",
  "Kiribati": "Kiribati",
  "Kosovo": "Kosovo",
  "Kuwait": "Koweït",
  "Kyrgyzstan": "Kirghizistan",
  "Laos": "Laos",
  "Latvia": "Lettonie",
  "Lebanon": "Liban",
  "Lesotho": "Lesotho",
  "Liberia": "Libéria",
  "Libya": "Libye",
  "Liechtenstein": "Liechtenstein",
  "Luxembourg": "Luxembourg",
  "Macao": "Macao",
  "Madagascar": "Madagascar",
  "Malawi": "Malawi",
  "Malaysia": "Malaisie",
  "Maldives": "Maldives",
  "Mali": "Mali",
  "Malta": "Malte",
  "Marshall Islands": "Îles Marshall",
  "Martinique": "Martinique",
  "Mauritania": "Mauritanie",
  "Mauritius": "Maurice",
  "Mayotte": "Mayotte",
  "Mexico": "Mexique",
  "Monaco": "Monaco",
  "Mongolia": "Mongolie",
  "Montenegro": "Monténégro",
  "Montserrat": "Montserrat",
  "Morocco": "Maroc",
  "Mozambique": "Mozambique",
  "Myanmar": "Myanmar",
  "Namibia": "Namibie",
  "Nauru": "Nauru",
  "Nepal": "Népal",
  "Netherlands": "Pays-Bas",
  "New Caledonia": "Nouvelle-Calédonie",
  "New Zealand": "Nouvelle-Zélande",
  "Nicaragua": "Nicaragua",
  "Niger": "Niger",
  "Nigeria": "Nigéria",
  "Niue": "Niue",
  "Norfolk Island": "Île Norfolk",
  "Northern Mariana Islands": "Îles Mariannes du Nord",
  "North Korea": "Corée du Nord",
  "North Macedonia": "Macédoine du Nord",
  "Norway": "Norvège",
  "Oman": "Oman",
  "Pakistan": "Pakistan",
  "Palau": "Palaos",
  "Palestine": "Palestine",
  "Panama": "Panama",
  "Papua New Guinea": "Papouasie-Nouvelle-Guinée",
  "Paraguay": "Paraguay",
  "Peru": "Pérou",
  "Philippines": "Philippines",
  "Pitcairn Islands": "Îles Pitcairn",
  "Poland": "Pologne",
  "Portugal": "Portugal",
  "Puerto Rico": "Porto Rico",
  "Qatar": "Qatar",
  "Republic of Lithuania": "République de Lituanie",
  "Republic of Moldova": "République de Moldavie",
  "Republic of the Congo": "République du Congo",
  "Réunion": "Réunion",
  "Romania": "Roumanie",
  "Russia": "Russie",
  "Rwanda": "Rwanda",
  "Saint Barthélemy": "Saint-Barthélemy",
  "Saint Helena": "Sainte-Hélène",
  "Saint Lucia": "Sainte-Lucie",
  "Saint Martin": "Saint-Martin",
  "Saint Pierre and Miquelon": "Saint-Pierre-et-Miquelon",
  "Saint Vincent and the Grenadines": "Saint-Vincent-et-les-Grenadines",
  "Samoa": "Samoa",
  "San Marino": "Saint-Marin",
  "São Tomé and Príncipe": "São Tomé-et-Príncipe",
  "Saudi Arabia": "Arabie saoudite",
  "Senegal": "Sénégal",
  "Serbia": "Serbie",
  "Seychelles": "Seychelles",
  "Sierra Leone": "Sierra Leone",
  "Singapore": "Singapour",
  "Sint Maarten": "Sint Maarten",
  "Slovakia": "Slovaquie",
  "Slovenia": "Slovénie",
  "Solomon Islands": "Îles Salomon",
  "Somalia": "Somalie",
  "South Africa": "Afrique du Sud",
  "South Georgia and the South Sandwich Islands":
      "Géorgie du Sud et îles Sandwich du Sud",
  "South Korea": "Corée du Sud",
  "South Sudan": "Soudan du Sud",
  "Spain": "Espagne",
  "Sri Lanka": "Sri Lanka",
  "St Kitts and Nevis": "Saint-Christophe-et-Niévès",
  "Sudan": "Soudan",
  "Suriname": "Suriname",
  "Svalbard and Jan Mayen": "Svalbard et Jan Mayen",
  "Sweden": "Suède",
  "Switzerland": "Suisse",
  "Syria": "Syrie",
  "Taiwan": "Taïwan",
  "Tajikistan": "Tadjikistan",
  "Tanzania": "Tanzanie",
  "Thailand": "Thaïlande",
  "Togo": "Togo",
  "Tokelau": "Tokelau",
  "Tonga": "Tonga",
  "Trinidad and Tobago": "Trinité-et-Tobago",
  "Tunisia": "Tunisie",
  "Turkey": "Turquie",
  "Turkmenistan": "Turkménistan",
  "Turks and Caicos Islands": "Îles Turques-et-Caïques",
  "Tuvalu": "Tuvalu",
  "Uganda": "Ouganda",
  "Ukraine": "Ukraine",
  "United Arab Emirates": "Émirats arabes unis",
  "Uruguay": "Uruguay",
  "U.S. Minor Outlying Islands": "Îles mineures éloignées des États-Unis",
  "U.S. Virgin Islands": "Îles Vierges américaines",
  "Uzbekistan": "Ouzbékistan",
  "Vanuatu": "Vanuatu",
  "Vatican City": "Cité du Vatican",
  "Venezuela": "Venezuela",
  "Vietnam": "Vietnam",
  "Wallis and Futuna": "Wallis-et-Futuna",
  "Western Sahara": "Sahara occidental",
  "Yemen": "Yémen",
  "Zambia": "Zambie",
  "Zimbabwe": "Zimbabwe"
};
