import 'dart:convert';
import 'dart:io';

class Base64Util {
  /// 将字符串编码为 Base64
  static String encode(String data) {
    return base64.encode(utf8.encode(data));
  }

  /// 将 Base64 解码为字符串
  static String decode(String data) {
    return utf8.decode(base64.decode(data));
  }



  /// 将 JSON 对象编码为 Base64
  static String encodeJson(Map<String, dynamic> json) {
    return encode(jsonEncode(json));
  }

  static dynamic decodeJson(String data) {
    return jsonDecode(decode(data));
  }

  /// 格式化并打印 JSON 对象
  static void printFormattedJson(dynamic json) {
    const JsonEncoder encoder = JsonEncoder.withIndent('  ');
    print(encoder.convert(json));
  }

  /// 解码 Base64 并格式化打印 JSON
  static void decodeAndPrintJson(String base64Data) {
    try {
      dynamic json = jsonDecode(utf8.decode(base64.decode(base64Data)));
      const JsonEncoder encoder = JsonEncoder.withIndent('  ');
      print(encoder.convert(json));
    } catch (e) {
      print("Error decoding or parsing JSON: $e");
    }
  }

  /// 从控制台读取 JSON 输入
  static Map<String, dynamic>? readJsonFromConsole() {
    print(
        "请输入 JSON 数据（输入完成后请按回车键，然后输入 'END' 并再次按回车结束输入）：");
    String jsonString = "";
    while (true) {
      String? line = stdin.readLineSync();
      if (line?.trim().toUpperCase() == 'END') break;
      if (line != null) jsonString += line;
    }

    if (jsonString
        .trim()
        .isEmpty) {
      print("输入为空，请重新运行程序并输入有效的 JSON 数据。");
      return null;
    }

    try {
      return jsonDecode(jsonString);
    } catch (e) {
      print("JSON 解析错误：$e");
      print("请确保输入的是有效的 JSON 格式。");
      return null;
    }
  }

  String decodeBase64ToJson(String base64String) {
    try {
      List<int> bytes = base64.decode(base64String);
      String jsonString = utf8.decode(bytes);
      return jsonString;
    } catch (e) {
      return "Error decoding Base64: $e";
    }
  }
}

void main() {
  String base64Data = "eyJDb21tb25BbnN3ZXJlZENvdW50IjowLCJhYlRlc3RBc3NpZ24iOm51bGwsImFib3V0IjoiIiwiYWdlIjoiMjMiLCJhZ3JlZUd1aWRlbGluZXMiOiIwIiwiYWdyZWVOb09ubGluZU9ubHkiOiIwIiwiYWdyZWVQcHNhIjoiMSIsImFncmVlVGVub3JQcml2YWN5UG9saWN5IjoiMCIsImFncmVlZFBwc2FJZCI6IiIsImF1dG9SZW5ldyI6MCwiYXZhdGFyIjoiaHR0cHM6Ly9waWMudm9pY2VzZGF0aW5nLmNvbS9hdmF0YXIvZ2VuZGVyMS5wbmciLCJhdmF0YXJSZWNhbGxDaGFsbGVuZ2VVc2VyTGV2ZWwiOiIiLCJiZGF0ZUdhbGxlcnkiOltdLCJiaXJ0aGRheSI6OTc4MzM2MDAwLCJib2R5IjoiIiwiYm9keVNoYXBlU3RvcnkiOnt9LCJib2xkR2FsbGVyeSI6W10sImJ1c2luZXNzU3RvcnkiOnt9LCJjYW5TZW5kVmVyaWZ5UGhvdG8iOjEsImNhblNraXBWZXJpZnlQaG9uZSI6MCwiY2FuVXBsb2FkVmlkZW8iOjEsImNhbldpbmsiOjAsImNoYW5nZWRCaXJ0aGRheSI6IjAiLCJjaGFuZ2VkR2VuZGVyIjoiMCIsImNvaW5zIjowLCJjb21tdW5pdHlBYmJyIjoiIiwiY291bnRyeUdyb3VwIjoxLCJjb3ZlciI6W10sImNvdmlkMTlWYWNjaW5lIjoiMCIsImNyZWF0ZWQiOjE3MjcwNTY4MDQsImN1ckxvY2F0aW9uIjp7ImNpdHkiOiJDaGVuZ2R1IiwiY2l0eUlkIjoiMjU2NTUiLCJjb3VudEFiYnIiOiJDTiIsImNvdW50Q29kZSI6IkNITiIsImNvdW50cnkiOiJDaGluYSIsImNvdW50cnlJZCI6IjQ3IiwiY3VyQWRkcmVzcyI6IiIsImxhdGl0dWRlIjoiIiwibG9uZ2l0dWRlIjoiIiwic3RhdGUiOiJTaWNodWFuIiwic3RhdGVBYmJyIjoiU0MiLCJzdGF0ZUlkIjoiNjM1In0sImN1c3RvbUFsYnVtIjpbXSwiY3VzdG9taXplZFdpbmtzIjpbXSwiZGVmYXVsdFdpbmtUeXBlSWQiOiIiLCJkZXRhaWxPY2N1cGF0aW9uIjoiIiwiZGlzYWJpbGl0eSI6IjAiLCJkaXNhYmxlU2NyZWVuc2hvdCI6IjAiLCJkcmluayI6IiIsImVkdWNhdGlvbiI6IiIsImVtYWlsIjoiZGF2aWRsaUB0ZXN0ZXIuODh2aXAuc2l0ZSIsImVtYWlsVW5zdWJzY3JpYmUiOiIwIiwiZW1haWxWZXJpZmllZCI6IjEiLCJlbmFibGVNb21lbnRTeW5jIjoiMSIsImV0aG5pY2l0eSI6IiIsImV4aXN0QmxvZyI6MCwiZXhwaXJlZERhdGUiOjAsImV5ZXMiOiIiLCJmYWNlYm9va1VpZCI6IiIsImZhdm9yaXRlQ2F0ZWdvcnkiOltdLCJmYXZvcml0ZU11c2ljIjoiMCIsImZyYXVkU3RhdHVzIjoiMCIsImZyaWVuZGx5Sm9rZSI6IiIsImZyaWVuZGx5Sm9rZUNudCI6MCwiZnJvbUFjdGl2aXR5IjoiMCIsImZ1blF1ZXN0aW9uQW5zd2VyIjpudWxsLCJnZW5kZXIiOiIxIiwiZ29vZ2xlRW1haWwiOiIiLCJnb29nbGVQbGF5Tm90aWZ5U3RhdHVzIjpudWxsLCJnb29nbGVVaWQiOiIiLCJoYWlyIjoiIiwiaGFzQXBwcm92ZWRJZGVhIjoiMCIsImhhc0Jsb2ciOjAsImhhc0NvbXBhbmlvbkV2ZW50IjowLCJoYXNNb21lbnQiOjAsImhhc1N1YnNjcmlwdGlvbiI6ZmFsc2UsImhhdmVDaGlsZHJlbiI6IiIsImhhdmVQZXQiOiIwIiwiaGVhZGxpbmUiOiIiLCJoZWlnaHQiOiIxNzciLCJoaWRkZW4iOiIxIiwiaGlkZGVuQWN0aXZpdHkiOiIwIiwiaGlkZGVuQ3VycmVudExvY2F0aW9uIjoiMCIsImhpZGRlbkRpc2FiaWxpdHkiOiIwIiwiaGlkZGVuRnJvbUdlbmRlciI6IjAiLCJoaWRkZW5HZW5kZXIiOiIwIiwiaGlkZGVuTG9naW4iOiIwIiwiaGlkZGVuT25saW5lIjoiMCIsImhpZGRlblBob3RvIjoiMCIsImhpZGRlblBob3RvRXhjZXB0TGlrZUFuZEhhZFBob3RvcyI6IjAiLCJoaWRkZW5QaG90b0V4Y2VwdExpa2VBbmRQcmVtaXVtIjoiMCIsImhpZGRlblBob3RvRXhjZXB0TGlrZU9ubHkiOiIwIiwiaGlkZGVuUGhvdG9Gcm9tR2VuZGVyIjpbXSwiaGlkZGVuVmVyaWZ5VmlkZW8iOjAsImhpZGRlblZpZXciOiIwIiwiaG9iYmllc0FuZEludGVyZXN0cyI6W10sImhvYmJ5IjoiMCIsImhvbGRXYWl0aW5nRm9yVmVyaWZ5IjpmYWxzZSwiaG9tZXRvd24iOiIiLCJpbXBlcnNvbmF0ZSI6MCwiaW5jb21lIjoiIiwiaW5zUGhvdG9zIjpbXSwiaXNCb29zdCI6IjAiLCJpc09wZW5Qcm9maWxlIjoiMCIsImlzT3BlblVzZXJTZW5kaW5nV2lua3MiOiIxIiwiaXNQYWlkIjpmYWxzZSwiaXNSYW5kb21OYW1lIjoiMCIsImlzUmVhZFJlY2VpcHQiOiIwIiwiaXNTY3JlZW5zaG90QWxsb3dlZCI6IjEiLCJpc1ZvdGVDaGFybSI6MCwibGFuZ3VhZ2UiOiIwIiwibGFzdEFjdGl2ZVRpbWUiOiIxNzI3MDU2ODA0IiwibGFzdFBheU1vbnRocyI6bnVsbCwibGFzdFBheVdheSI6bnVsbCwibGFzdFByb2ZpbGVDb21tZW50IjpbXSwibGFzdFRpbWVsaW5lIjpbeyJhZ2UiOiIyMyIsImFncmVlZFNoYXJlIjoiMCIsImFub255bW91c1N0YXR1cyI6IjAiLCJhdmF0YXIiOiJodHRwczovL3BpYy52b2ljZXNkYXRpbmcuY29tL2F2YXRhci9nZW5kZXIxLnBuZyIsImF2YXRhckhlaWdodCI6MSwiYXZhdGFyVGh1bWIiOiJodHRwczovL3BpYy52b2ljZXNkYXRpbmcuY29tL2F2YXRhci9nZW5kZXIxLnBuZyIsImF2YXRhcldpZHRoIjoxLCJibG9ja2VkIjowLCJibG9ja2VkTWUiOjAsImNpdHkiOiIiLCJjb21tZW50cyI6W10sImNvbW1lbnRzQ291bnQiOiIwIiwiY291bnRBYmJyIjoiVVMiLCJjb3VudENvZGUiOiJVU0EiLCJjb3VudHJ5IjoiVW5pdGVkIFN0YXRlcyIsImNyZWF0ZWRGb3JtYXQiOiJqdXN0IG5vdyEiLCJjcm9wSW5mbyI6bnVsbCwiZGlzYWJpbGl0eSI6IiIsImV0aG5pY2l0eSI6IjAiLCJldmVudFN1YmplY3QiOiIiLCJmb2xsb3dTdGF0dXMiOjAsImZyb21QbGFuZXRJZCI6IiIsImdlbmRlciI6IjEiLCJnaWZ0TmFtZSI6IiIsImdpZnRQcmljZSI6IjAiLCJoYXNodGFncyI6W10sImhpZGRlbiI6IjEiLCJoaWRkZW5HZW5kZXIiOiIwIiwiaXNTaWx2ZXIiOjAsIml0aW5lcmFyeUluZm8iOltdLCJsaWtlZCI6MCwibGlrZWRDbnQiOjAsImxpa2VkTWUiOjAsImxpa2VycyI6IiIsIm1lbWJlciI6IjAiLCJtb29kIjoiIiwib25saW5lIjoiMCIsInBob3RvQ250IjowLCJwb2xsRW5kVGltZSI6MCwicG9sbExlZnRUaW1lIjowLCJwb2xsT3B0aW9ucyI6W10sInJlcG9ydGVkIjoiMCIsInN0YXRlIjoiQXJpem9uYSIsInN0YXRlQWJiciI6IkFaIiwidGFnIjoiIiwidGltZWxpbmVEYXRlIjoxNzI3MDU2ODA0LCJ0aW1lbGluZURlc2NyIjoiSm9pbmVkIG9uIFNlcHRlbWJlciAyMiwgMjAyNCIsInRpbWVsaW5lSWQiOiIzMzY3NzAwOSIsInRpbWVsaW5lUGlubmVkIjoiMCIsInRpbWVsaW5lU3RhdHVzIjoiMSIsInRpbWVsaW5lU3ViamVjdCI6IiIsInRpbWVsaW5lVHlwZSI6IjEiLCJ0aW1lbGluZVR5cGVEZXNjciI6ImpvaW5lZCB0aGUgc2l0ZSBvbiIsInVzZXJJZCI6IjczMTkxMDA3IiwidXNlcm5hbWUiOiJldGVybml0eTAwMyIsInZlcmlmaWVkIjoiMCIsInZpZGVvVGltZSI6Imp1c3Qgbm93ISIsInZpZGVvVmlld3MiOjAsInZvdGVDb3VudCI6MH1dLCJsY0NpZCI6bnVsbCwibGNDc3QiOm51bGwsImxlZnRTdXBlckxpa2UiOjAsImxpa2VNZVR5cGUiOjAsImxpa2VUeXBlIjowLCJsaWtlZCI6MCwibGlrZWRDbnRUb2RheSI6MCwibGlrZWRNZSI6MCwibG9jYXRpb24iOnsiY2l0eSI6IiIsImNpdHlJZCI6MCwiY291bnRBYmJyIjoiVVMiLCJjb3VudENvZGUiOiJVU0EiLCJjb3VudHJ5IjoiVW5pdGVkIFN0YXRlcyIsImNvdW50cnlJZCI6IjIzNyIsImN1ckFkZHJlc3MiOiIiLCJsYXRpdHVkZSI6IiIsImxvbmdpdHVkZSI6IiIsInN0YXRlIjoiQXJpem9uYSIsInN0YXRlQWJiciI6IkFaIiwic3RhdGVJZCI6IjQyMzQifSwibG9jYXRpb25BY2Nlc3MiOiIwIiwibG9jYXRpb25Db25maXJtZWQiOiIwIiwibHV4dXJ5QWxidW0iOltdLCJtYWluVmlkZW8iOm51bGwsIm1hbmRhdG9yeVZlcmlmaWNhdGlvbkZsYWciOiIwIiwibWFuZGF0b3J5VmVyaWZpY2F0aW9uUGhvbmVGbGFnIjoiMCIsIm1hcml0YWwiOiIiLCJtYXRjaEFib3V0IjoiIiwibWF0Y2hBZ2UiOnsibWF4IjoiOTkiLCJtaW4iOiIxOSJ9LCJtYXRjaEFueXdoZXJlIjoiMSIsIm1hdGNoQ2l0eUlkIjoiIiwibWF0Y2hDb3VudHJ5SWQiOiIyMzciLCJtYXRjaERpc3RhbmNlIjoiIiwibWF0Y2hHZW5kZXIiOiIzIiwibWF0Y2hJbmNvbWUiOiIiLCJtYXRjaExhbmd1YWdlIjoiMCIsIm1hdGNoUmVsYXRpb25zaGlwIjoiMCIsIm1hdGNoU3RhdGVJZCI6IiIsIm1lbWJlciI6IjAiLCJtdXNpYyI6e30sIm15QnVzaW5lc3MiOltdLCJteUJ1c2luZXNzQWxidW0iOltdLCJteUZhdm9yaXRlRGFpbHlRdW90ZXMiOltdLCJteVF1ZXN0aW9uIjp7InF1ZXN0aW9uIjoiIiwicXVlc3Rpb25Db3VudCI6MH0sIm5lZWRWZXJpZnlQaG9uZSI6MCwibmV0V29ydGgiOiIiLCJuZXdVc2VyQ2hhdHJvb21JZCI6bnVsbCwibm9NYWluUGhvdG8iOiIwIiwibm90aWNlTGlrZSI6IjEiLCJub3RpY2VNZXNzYWdlIjoiMSIsIm5vdGljZVZpZXciOiIxIiwib2NjdXBhdGlvbiI6IiIsIm9ubGluZSI6IjAiLCJvcGVuQXV0b1JlcGx5TXNnIjoiMCIsIm9wZXJhdGlvbmFsQWN0aXZpdGllc0VtYWlsVW5zdWJzY3JpYmUiOiIwIiwicGF5bWVudFN0YXJ0RGF0ZSI6MCwicGF5bWVudFN0YXJ0RGF0ZVQiOiJEZWMtMzEtNjkiLCJwZXJmZWN0RGF0ZSI6W10sInBlcmZlY3RMaWtlTGlzdCI6W10sInBlcmZlY3RMaWtlU3RhdHVzIjoiMCIsInBlcnNvbmFsaXR5IjoiMCIsInBlcnNvbmFsaXR5RGVzYyI6IiIsInBldCI6IiIsInBldEFsYnVtIjpbXSwicGV0SW5mbyI6W10sInBob25lIjoiIiwicGhvbmVDb3VudHJ5IjoiIiwicGhvbmVWZXJpZmllZCI6IjEiLCJwaG90b3MiOltdLCJwbGF0Zm9ybSI6IjMiLCJwb2xpdGljYWxCZWxpZWYiOiIiLCJwb3B1cFN0YXR1c0ZvckRhdGFUaXBzIjoiMCIsInByZXZpb3VzUGF5bWVudHN0YXR1cyI6MiwicHJpdmF0ZUFsYnVtIjpbXSwicHJpdmF0ZVZpZGVvIjpbXSwicHJvZmlsZUNvbW1lbnROdW1iZXIiOiIwIiwicHJvZmlsZUxpa2VkQ250IjpbeyJkZXNjciI6IkFCT1VUIE1FIiwiaWQiOjEsImxpa2VjbnQiOjAsImxpa2VkIjowfSx7ImRlc2NyIjoiTVkgTUFUQ0giLCJpZCI6MiwibGlrZWNudCI6MCwibGlrZWQiOjB9LHsiZGVzY3IiOiJIT0JCSUVTXHUwMDI2SU5URVJFU1RTIiwiaWQiOjMsImxpa2VjbnQiOjAsImxpa2VkIjowfSx7ImRlc2NyIjoiQlVTSU5FU1NcdTAwMjZDQVJFRVIiLCJpZCI6NCwibGlrZWNudCI6MCwibGlrZWQiOjB9LHsiZGVzY3IiOiJIRUFETElORSIsImlkIjo1LCJsaWtlY250IjowLCJsaWtlZCI6MH0seyJkZXNjciI6IkZSSUVORExZIFNVR0FSIEpPS0VTIiwiaWQiOjYsImxpa2VjbnQiOjAsImxpa2VkIjowfSx7ImRlc2NyIjoiSE9XIEkgS0VFUCBNWSBCT0RZIElOIFNIQVBFIiwiaWQiOjcsImxpa2VjbnQiOjAsImxpa2VkIjowfV0sInByb2ZpbGVQZW5kaW5nIjoxLCJwcm9maWxlVmlkZW8iOltdLCJwcm9tcHRJZk5vUGhvdG8iOnsiZG9udF9yZW1pbmRfbm9ucGhvdG8iOiIwIiwibm9ucGhvdG9fdXBkYXRlX3RpbWUiOiIxNzI3MDU2ODA0In0sInB1YmxpY1ZpZGVvIjpbXSwicHVzaGVkQXBwc2ZseWVyVXNlcklkIjoiTnpNeE9URXdNRGM9IiwicXVlc3Rpb24iOnsiYW5zd2VyZWRDb3VudCI6MCwicXVlc3Rpb24iOiJXaGF0IGFyZSB5b3VyIGV4cGVjdGF0aW9ucyBmcm9tIHRoZSBhcnJhbmdlbWVudD8ifSwicmVhbEZhY2UiOltdLCJyZWFsU2VsZmllQWxidW0iOltdLCJyZWdEYXlzIjowLCJyZWxhdGlvbiI6IjAiLCJyZWxpZ2lvbiI6IiIsInJlbWFpbmluZ0RheSI6MCwicmVzdG9yZUlkIjoiIiwicmlkZVdheXMiOiIwIiwic2Nob29sIjoiIiwic2Nob29sUGVuZGluZyI6IiIsInNleHVhbGl0eSI6IiIsInNob3J0VmlkZW9DbnQiOjAsInNob3dHbG9iYWxQcm9maWxlIjoxLCJzaWduIjoiIiwic21va2UiOiIiLCJzb3VyY2VBYmJyIjoiIiwic291cmNlQ2xvbmVBYmJyIjoiIiwic3RhdHVzIjoiMCIsInN0b3J5T2ZDaGFyaXR5IjpbXSwic3dpdGNoZWRBYmJyIjoiIiwidGhpbmdzUmVjb21tZW5kVG9Db21tdW5pdHkiOnt9LCJ0aW1lTGluZVN0YXR1cyI6IjAiLCJ0cmFja0lkIjoiIiwidXNlckN1c3RvbWl6ZWRGYXZvcml0ZXMiOnt9LCJ1c2VySWQiOiI3MzE5MTAwNyIsInVzZXJSYXRlcyI6MCwidXNlclRyYWZmaWNMYWJlbCI6Im9yZ2FuaWMiLCJ1c2VybmFtZSI6ImV0ZXJuaXR5MDAzIiwidXNySWQiOiIiLCJ2ZXJpZmllZCI6IjAiLCJ2ZXJpZmllZENoYXJpdHkiOiIiLCJ2ZXJpZmllZEVudmlyb25tZW50YWwiOiIwIiwidmVyaWZpZWRJbmNvbWUiOiIwIiwidmVyaWZpZWRJbmNvbWVUeXBlIjoiMSIsInZpZGVvSWQiOiIiLCJ2aWV3ZWRDcm9wIjoiMCIsInZpcFZlcmlmeSI6IiIsInZvaWNlIjpudWxsLCJ3YW50Q2hpbGRyZW4iOiIiLCJ3aW5rZWQiOjAsIndpc2hsaXN0IjpbXX0=";
  try {
    dynamic decodedData = Base64Util.decodeJson(base64Data);
    Base64Util.printFormattedJson(decodedData);
  } catch (e) {
    print("Error decoding or parsing JSON: $e");
  }
}